stages:
  - build

variables:
  DOCKER_REGISTRY: "${CI_REGISTRY}"
  DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}"
  DOCKER_TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKER_USERNAME: "gitlab-ci-token"
  DOCKER_PASSWORD: "${CI_JOB_TOKEN}"

build:
  stage: build
  only:
    - branches
  script: |
    docker info
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"
    docker build --pull -t "${DOCKER_IMAGE}:${DOCKER_TAG}" .
    docker push "${DOCKER_IMAGE}:${DOCKER_TAG}"
    # tag master as latest
    if [ "${CI_COMMIT_REF_NAME}" == "master" ];then
      docker tag "${DOCKER_IMAGE}:${DOCKER_TAG}" "${DOCKER_IMAGE}:latest"
      docker push "${DOCKER_IMAGE}:latest"
    fi
